spring:
  rabbitmq:
    username: guest
    password: guest
    host: grey-dragon.local
    port: 5672
    virtualhost: /test
    stream:
      host: grey-dragon.local
    publisher-confirm-type: CORRELATED
    publisher-returns: true